packages:
  - "packages/*"

allowBuilds:
  esbuild: true

catalog:
  solid-js: 2.0.0-beta.16
  "@solidjs/signals": 2.0.0-beta.16
  "@solidjs/web": 2.0.0-beta.16

minimumReleaseAgeExclude:
  - vite@8.1.4
  - '@storybook/addon-a11y@10.5.0'
  - '@storybook/addon-docs@10.5.0'
  - '@storybook/csf-plugin@10.5.0'
  - '@storybook/react-dom-shim@10.5.0'
  - storybook@10.5.0
