export enum EventKeys {
  "ArrowDown" = "ArrowDown",
  "ArrowUp" = "ArrowUp",
  "ArrowLeft" = "ArrowLeft",
  "ArrowRight" = "ArrowRight",
  "Enter" = "Enter",
  "Space" = " ",
  "Tab" = "Tab",
  "Backspace" = "Backspace",
  "Control" = "Control",
  "Meta" = "Meta",
  "Home" = "Home",
  "End" = "End",
  "PageDown" = "PageDown",
  "PageUp" = "PageUp",
  "Delete" = "Delete",
  "Escape" = "Escape",
  "Shift" = "Shift",
}
