import { createGlobalThemeContract } from "@vanilla-extract/css";

const colorPaletteContract = {
  1: null,
  2: null,
  3: null,
  4: null,
  5: null,
  6: null,
  7: null,
  8: null,
  9: null,
  10: null,
  11: null,
  12: null,
};

export const spaceContract = {
  "0.5": null,
  "1": null,
  "1.5": null,
  "2": null,
  "2.5": null,
  "3": null,
  "3.5": null,
  "4": null,
  "5": null,
  "6": null,
  "7": null,
  "8": null,
  "9": null,
  "10": null,
  "12": null,
  "14": null,
  "16": null,
  "20": null,
  "24": null,
  "28": null,
  "32": null,
  "36": null,
  "40": null,
  "44": null,
  "48": null,
  "52": null,
  "56": null,
  "60": null,
  "64": null,
  "72": null,
  "80": null,
  "96": null,
};

function mapTokenName(_value: string | null, path: string[]): string {
  return `hope-${path.join("-")}`.replace(".", "_");
}

export const baseContract = createGlobalThemeContract(
  {
    space: spaceContract,
    sizes: {
      ...spaceContract,
      prose: null,
      xs: null,
      sm: null,
      md: null,
      lg: null,
      xl: null,
      "2xl": null,
      "3xl": null,
      "4xl": null,
      "5xl": null,
      "6xl": null,
      "7xl": null,
      "8xl": null,
      container: {
        sm: null,
        md: null,
        lg: null,
        xl: null,
        "2xl": null,
      },
    },
    fonts: {
      sans: null,
      serif: null,
      mono: null,
    },
    fontSizes: {
      xs: null,
      sm: null,
      base: null,
      lg: null,
      xl: null,
      "2xl": null,
      "3xl": null,
      "4xl": null,
      "5xl": null,
      "6xl": null,
      "7xl": null,
      "8xl": null,
      "9xl": null,
    },
    fontWeights: {
      hairline: null,
      thin: null,
      light: null,
      normal: null,
      medium: null,
      semibold: null,
      bold: null,
      extrabold: null,
      black: null,
    },
    lineHeights: {
      none: null,
      shorter: null,
      short: null,
      base: null,
      tall: null,
      taller: null,
      "3": null,
      "4": null,
      "5": null,
      "6": null,
      "7": null,
      "8": null,
      "9": null,
      "10": null,
    },
    letterSpacings: {
      tighter: null,
      tight: null,
      normal: null,
      wide: null,
      wider: null,
      widest: null,
    },
    radii: {
      none: null,
      xs: null,
      sm: null,
      md: null,
      lg: null,
      xl: null,
      "2xl": null,
      "3xl": null,
      full: null,
    },
    zIndices: {
      underlay: null,
      overlay: null,
    },
  },
  mapTokenName
);

export const colorContract = createGlobalThemeContract(
  {
    colors: {
      primary: colorPaletteContract,
      accent: colorPaletteContract,
      neutral: colorPaletteContract,
      success: colorPaletteContract,
      info: colorPaletteContract,
      warning: colorPaletteContract,
      danger: colorPaletteContract,
      focusRing: null,
      background: null,
    },
    shadows: {
      xs: null,
      sm: null,
      md: null,
      lg: null,
      xl: null,
      "2xl": null,
      "3xl": null,
    },
  },
  mapTokenName
);

export const vars = { ...baseContract, ...colorContract };
