import { type Accessor, onSettled } from "solid-js";

export interface CreateRegisteredIdOptions {
  /**
   * The id to publish. `false` and `undefined` both register nothing — `false` is
   * dom-expressions' "omit this attribute" convention, and Solid types every `id` prop as
   * `string | false | undefined`.
   */
  id: Accessor<string | false | undefined>;
  /** Receives the id once mounted, and `undefined` on cleanup. */
  register: (id: string | undefined) => void;
}

/**
 * Publishes a descendant's `id` into an ancestor's context, so the ancestor can point an
 * ARIA relationship (`aria-labelledby`, `aria-describedby`, `aria-controls`, …) at an
 * element it doesn't own.
 *
 * The deferral is the whole primitive. SolidJS 2.0 throws `[REACTIVE_WRITE_IN_OWNED_SCOPE]`
 * when a descendant writes to a signal owned by an ancestor's reactive scope directly from
 * its own synchronous render body — which is exactly what "register my id with my parent"
 * is. `onSettled` moves the write out of that owned-scope call stack.
 *
 * This is easy to get wrong by copy-paste: the naive `context.setTitleId(id)` in the body
 * looks right, works in a trivial test, and throws in a real tree. Hence a primitive rather
 * than a snippet.
 *
 * The id is read **once**, after mount — matching how ARIA-linking ids are used in
 * practice (generated by `createUniqueId` or pinned by the consumer, never animated).
 *
 * ## SSR
 *
 * `onSettled` never runs during SSR, so nothing is registered server-side. A component
 * whose server-rendered markup must already carry the linked attribute therefore needs its
 * *own* server-visible fallback (see `Dialog.Root`'s generated `popupId`). Where the
 * registering component only ever renders inside a `Portal` — which doesn't render
 * server-side at all — there is no server value to disagree with, and hydration is safe by
 * construction.
 */
export function createRegisteredId(options: CreateRegisteredIdOptions): void {
  onSettled(() => {
    const id = options.id();
    options.register(typeof id === "string" ? id : undefined);
    return () => options.register(undefined);
  });
}
