import { renderToStringAsync } from "@solidjs/web";
import { describe, expect, it } from "vitest";
import { Flex } from "../flex";

describe("Flex SSR", () => {
  it("resolves renderToStringAsync without throwing", async () => {
    const html = await renderToStringAsync(() => <Flex>Flex content</Flex>);
    expect(typeof html).toBe("string");
  });

  it("maps the shorthands to atomic classes and keeps the content", async () => {
    const html = await renderToStringAsync(() => (
      <Flex direction="column" align="center" justify="space-between" gap="2">
        Flex content
      </Flex>
    ));
    expect(html).toContain("Flex content");
    expect(html).toMatch(/\bd_flex\b/);
    expect(html).toMatch(/\bflex-d_column\b/);
    expect(html).toMatch(/\bai_center\b/);
    expect(html).toMatch(/\bjc_space-between\b/);
    expect(html).toMatch(/\bgap_2\b/);
  });

  it("matches the committed SSR fixture byte for byte", async () => {
    // Half of the hydration round-trip, runnable only in the `ssr` project (both `solid-js` and
    // `@solidjs/web` resolve to their server builds here). Generated by a real server render via
    // `toMatchFileSnapshot` — never hand-written — so the `_hk` key and the deterministic Panda
    // class string are exactly what `hydrate()` matches on in `flex.browser.test.tsx`. Update
    // deliberately with `pnpm exec vitest run --project=ssr -u`. The rendered tree here MUST stay
    // structurally identical to the one hydrated in the browser test.
    const html = await renderToStringAsync(() => (
      <Flex direction="column" align="center" justify="space-between" gap="2">
        Flex content
      </Flex>
    ));
    await expect(html).toMatchFileSnapshot("./__fixtures__/flex-ssr.html");
  });
});
