/*
 * @hope-ui/themes/hope/recipes — the runtime recipe map for the hope theme.
 *
 * This is the JS half of a hope-ui theme (the CSS half is `@import "@hope-ui/themes/hope"`). A
 * SolidJS app passes it to `<ThemeProvider theme={hopeRecipes}>`; `@hope-ui/components` then reads
 * each component's recipe out with `useRecipe(...)`. The recipe *functions* here produce the class
 * names at runtime; the matching CSS is generated by the consumer's Tailwind build scanning
 * `./recipes` (see `../theme.css`).
 *
 * `satisfies RecipeRegistry` checks the map against `@hope-ui/theming`'s contract — every recipe the
 * contract requires is present and shaped correctly — while keeping each recipe's precise type.
 */
import type { RecipeRegistry } from "@hope-ui/theming";
import { buttonRecipe } from "./button";

/** The hope theme's recipe map — every component recipe hope implements, keyed by component name. */
export const hopeRecipes = {
  button: buttonRecipe,
} satisfies RecipeRegistry;
