import { renderToStringAsync } from "@solidjs/web";
import { describe, expect, it } from "vitest";
import { Box } from "../box";

describe("Box SSR", () => {
  it("resolves renderToStringAsync without throwing", async () => {
    const html = await renderToStringAsync(() => <Box>Box content</Box>);
    expect(typeof html).toBe("string");
  });

  it("maps style props to atomic classes and keeps the content", async () => {
    const html = await renderToStringAsync(() => (
      <Box p="4" bg="primary" rounded="lg">
        Box content
      </Box>
    ));
    expect(html).toContain("Box content");
    expect(html).toMatch(/\bp_4\b/);
    expect(html).toMatch(/\bbg_primary\b/);
    expect(html).toMatch(/\bbdr_lg\b/);
  });

  it("matches the committed SSR fixture byte for byte", async () => {
    // Half of the hydration round-trip, and only the `ssr` project can run it (both
    // `solid-js` and `@solidjs/web` resolve to their server builds here). Generated by a
    // real server render via `toMatchFileSnapshot` — never hand-written — so the `_hk`
    // key and the (deterministic) Panda class string are exactly what `hydrate()` matches
    // on in `box.browser.test.tsx`. Update deliberately with
    // `pnpm exec vitest run --project=ssr -u`.
    const html = await renderToStringAsync(() => (
      <Box p="4" bg="primary" rounded="lg">
        Box content
      </Box>
    ));
    await expect(html).toMatchFileSnapshot("./__fixtures__/box-ssr.html");
  });
});
