/*
 * hope preset — the runtime recipe map (internal; re-exported from the public `@hope-ui/presets/hope` entry).
 *
 * This is the JS half of a hope-ui preset (the CSS half is `@import "@hope-ui/presets/hope/tailwind.css"`). A
 * SolidJS app passes the derived preset to `<ThemeProvider preset={hope}>` (see `../index.ts`);
 * `@hope-ui/components` then reads each component's recipe out with `useRecipe(...)`. The recipe *functions*
 * here produce the class
 * names at runtime; the matching CSS is generated by the consumer's Tailwind build scanning
 * `./recipes` (see `../tailwind.css`).
 *
 * `satisfies RecipeRegistry` checks the map against `@hope-ui/theming`'s contract — every recipe the
 * contract requires is present and shaped correctly — while keeping each recipe's precise type.
 */
import type { RecipeRegistry } from "@hope-ui/theming";
import { alertRecipe } from "./alert";
import { badgeRecipe } from "./badge";
import { buttonRecipe } from "./button";
import { closeButtonRecipe } from "./close-button";
import { dialogRecipe } from "./dialog";
import { listboxRecipe } from "./listbox";

/** The hope preset's recipe map — every component recipe hope implements, keyed by component name. */
export const hopeRecipes = {
  alert: alertRecipe,
  badge: badgeRecipe,
  button: buttonRecipe,
  closeButton: closeButtonRecipe,
  dialog: dialogRecipe,
  listbox: listboxRecipe,
} satisfies RecipeRegistry;
