/*
 * hope preset — the runtime recipe map (internal; re-exported from `@hope-ui/presets/hope`).
 *
 * The recipe *functions* here produce class names at runtime; the matching CSS is generated by the
 * consumer's Tailwind build scanning this folder (see `../tailwind.css`).
 *
 * `satisfies RecipeRegistry` checks the map against `@hope-ui/theming`'s contract — every required
 * recipe present and correctly shaped — while keeping each recipe's own precise type, which a plain
 * type annotation would widen away.
 */
import type { RecipeRegistry } from "@hope-ui/theming";
import { alertRecipe } from "./alert";
import { badgeRecipe } from "./badge";
import { buttonRecipe } from "./button";
import { calendarRecipe } from "./calendar";
import { closeButtonRecipe } from "./close-button";
import { comboboxRecipe } from "./combobox";
import { dialogRecipe } from "./dialog";
import { listboxRecipe } from "./listbox";
import { popoverRecipe } from "./popover";
import { selectRecipe } from "./select";

/** The hope preset's recipe map — every component recipe hope implements, keyed by component name. */
export const hopeRecipes = {
  alert: alertRecipe,
  badge: badgeRecipe,
  button: buttonRecipe,
  calendar: calendarRecipe,
  closeButton: closeButtonRecipe,
  combobox: comboboxRecipe,
  dialog: dialogRecipe,
  listbox: listboxRecipe,
  popover: popoverRecipe,
  select: selectRecipe,
} satisfies RecipeRegistry;
