/*
 * hope preset — the runtime recipe map (internal; re-exported from the public `@hope-ui/presets/hope` entry).
 *
 * This is the JS half of a hope-ui preset (the CSS half is `@import "@hope-ui/presets/hope/tailwind.css"`). A
 * SolidJS app passes it to `<ThemeProvider theme={hopeRecipes}>`; `@hope-ui/components` then reads
 * each component's recipe out with `useRecipe(...)`. The recipe *functions* here produce the class
 * names at runtime; the matching CSS is generated by the consumer's Tailwind build scanning
 * `./recipes` (see `../tailwind.css`).
 *
 * `satisfies RecipeRegistry` checks the map against `@hope-ui/theming`'s contract — every recipe the
 * contract requires is present and shaped correctly — while keeping each recipe's precise type.
 */
import type { RecipeRegistry } from "@hope-ui/theming";
import { buttonRecipe } from "./button";

/** The hope preset's recipe map — every component recipe hope implements, keyed by component name. */
export const hopeRecipes = {
  button: buttonRecipe,
} satisfies RecipeRegistry;
